import "@/styles/globals.css";
import type { Metadata } from "next";
import HeaderComponent from "@/components/Header";
import Footer from "@/components/Footer";
import ClientThemeProvider from "./theme_provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <head />
      <body className="flex h-full flex-col bg-zinc-50 dark:bg-black min-h-screen">
        <ClientThemeProvider>
          <div className="fixed inset-0 flex justify-center sm:px-8">
            <div className="flex w-full max-w-7xl lg:px-8">
              <div className="w-full bg-white ring-1 ring-zinc-100 dark:bg-zinc-900 dark:ring-zinc-300/20" />
            </div>
          </div>
          <div className="relative">
            <HeaderComponent />
            {children}
            <Footer />
          </div>
        </ClientThemeProvider>
      </body>
    </html>
  );
}

