"use client";
import HeaderComponent from "@/components/Header";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "focus-visible";
import { useEffect, useRef } from "react";
import Footer from "@/components/Footer";
import ClientThemeProvider from "./theme_provider";

const inter = Inter({ subsets: ["latin"] });

function usePrevious<T>(value: T): T | undefined {
  const ref = useRef<T>();

  useEffect(() => {
    ref.current = value;
  }, [value]);

  return ref.current;
}

type AppProps = {
  Component: React.ComponentType<any>;
  pageProps: any;
  router: any;
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientThemeProvider>
          <div className="fixed inset-0 flex justify-center sm:px-8">
            <div className="flex w-full max-w-7xl lg:px-8">
              <div className="w-full bg-white ring-1 ring-zinc-100 dark:bg-zinc-900 dark:ring-zinc-300/20" />
            </div>
          </div>
          <div className="relative">
            <HeaderComponent />
            {children}
            <Footer />
          </div>
        </ClientThemeProvider>
      </body>
    </html>
  );
}

